#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Copyright (c) 2014, Evelyn Mitchell
#  All Rights Reserved.

revision = '$Revision$'
rcsid = '$Id$'

if __name__ == "__main__":
    print "in zeitrep main"

